package salonesupn;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Materia extends javax.swing.JInternalFrame {

    public int idMateria;
    public String nombre_Materia;
    public int idSemestre;
    public String nivel;
    public int horas;
    ArrayList<Materia> materiasCreadas = new ArrayList<>();

    public Materia(int idMateria, String Nombre_Materia, int idSemestre, String nivel, int horas) {
        this.idMateria = idMateria;
        this.nombre_Materia = Nombre_Materia;
        this.idSemestre = idSemestre;
        this.nivel = nivel;
        this.horas = horas;
    }

    public int getIdMateria() {
        return idMateria;
    }

    public void setIdMateria(int idMateria) {
        this.idMateria = idMateria;
    }

    public String getNombre_Materia() {
        return nombre_Materia;
    }

    public void setNombre_Materia(String Nombre_Materia) {
        this.nombre_Materia = Nombre_Materia;
    }

    public int getIdSemestre() {
        return idSemestre;
    }

    public void setIdSemestre(int idSemestre) {
        this.idSemestre = idSemestre;
    }

    public String getNivel() {
        return nivel;
    }

    public void setNivel(String nivel) {
        this.nivel = nivel;
    }

    public int getHoras() {
        return horas;
    }

    public void setHoras(int horas) {
        this.horas = horas;
    }

    public boolean crearMateria() {
        Connection conn = Conexion.conectar();
        String sql = "insert into materia values (? ,? , ?, ?, ? )";
        try {
            PreparedStatement statement = conn.prepareStatement(sql);
            statement.setInt(1, Integer.parseInt(txtCodigoMateria.getText()));
            statement.setString(2, txtNombreMateria.getText());
            statement.setInt(3, Integer.parseInt(txtSemestreMateria.getText()));
            statement.setString(4, txtNivelMateria.getText());
            statement.setInt(5, Integer.parseInt(txtHorasMateria.getText()));
            int rowsInserted = statement.executeUpdate();
            conn.close();
            verMaterias();
            if (rowsInserted > 0) {
                return true;
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex);

            //JOptionPane.showMessageDialog(null, "Error insertando materia");
        }
        return false;
    }

    public ArrayList verMaterias() throws SQLException {
        limpiarTabla();
        materiasCreadas.clear();
        Connection conn = Conexion.conectar();
        String sql = "select * from materia";
        Statement statement = conn.createStatement();
        ResultSet result = statement.executeQuery(sql);
        while (result.next()) {
            int id = result.getInt(1);
            String name = result.getString(2);
            int semester = result.getInt(3);
            String level = result.getString(4);
            int hours = result.getInt(5);
            
            Materia m = new Materia(id, name, semester, level, hours);

            materiasCreadas.add(m);
        }
        try {
            String datos[][] = new String[materiasCreadas.size()][5];
            for (int i = 0; i < materiasCreadas.size(); i++) {
                datos[i][0] = String.valueOf(materiasCreadas.get(i).idMateria);
                datos[i][1] = materiasCreadas.get(i).nombre_Materia;                
                datos[i][2] = String.valueOf(materiasCreadas.get(i).idSemestre);
                datos[i][3] = materiasCreadas.get(i).nivel;
                datos[i][4] = String.valueOf(materiasCreadas.get(i).horas);
            }
            jTableMaterias.setModel(new javax.swing.table.DefaultTableModel(
                    datos, new String[]{
                    "Codigo Materia", "Nombre Materia", "Semestre", "Nivel", "Horas"
                }));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        return materiasCreadas;
    }

    public void limpiarTabla() {
        txtCodigoMateria.setText("");
        txtNombreMateria.setText("");
        txtSemestreMateria.setText("");
        txtNivelMateria.setText("");
        txtHorasMateria.setText("");
        String vacio[][] = {{"", "", "", "", ""}, {"", "", "", "", ""}};
        jTableMaterias.setModel(new javax.swing.table.DefaultTableModel(
                vacio, new String[]{
                    "Codigo Materia", "Nombre Materia", "Semestre", "Nivel", "Horas"
                }
        ));
    }

    public Materia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelCodigoMateria = new javax.swing.JLabel();
        jLabelNombreMateria = new javax.swing.JLabel();
        jLabelSemestreMateria = new javax.swing.JLabel();
        jLabelNivelMateria = new javax.swing.JLabel();
        jLabelHorasMateria = new javax.swing.JLabel();
        txtCodigoMateria = new javax.swing.JTextField();
        txtNombreMateria = new javax.swing.JTextField();
        txtSemestreMateria = new javax.swing.JTextField();
        txtNivelMateria = new javax.swing.JTextField();
        txtHorasMateria = new javax.swing.JTextField();
        jButtonCrear = new javax.swing.JButton();
        jButtonLeer = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMaterias = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Materia");
        setNormalBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Licenciatura en Música - UPN 2022 - Version 1");

        jLabelCodigoMateria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCodigoMateria.setText("Codigo Materia");
        jLabelCodigoMateria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelNombreMateria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreMateria.setText("Nombre Materia");
        jLabelNombreMateria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelSemestreMateria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSemestreMateria.setText("Ubicación Semestral");
        jLabelSemestreMateria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelNivelMateria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNivelMateria.setText("Nivel");
        jLabelNivelMateria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelHorasMateria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHorasMateria.setText("Horas Lectivas");
        jLabelHorasMateria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonCrear.setText("Crear");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        jButtonLeer.setText("Leer");
        jButtonLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeerActionPerformed(evt);
            }
        });

        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jTableMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo Materia", "Nombre Materia", "Semestre", "Nivel", "Horas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMaterias.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(jTableMaterias);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCodigoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNombreMateria))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSemestreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSemestreMateria))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNivelMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNivelMateria))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHorasMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHorasMateria)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jButtonCrear)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLeer)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimpiar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabelCodigoMateria, jLabelHorasMateria, jLabelNivelMateria, jLabelNombreMateria, jLabelSemestreMateria});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCodigoMateria, txtHorasMateria, txtNivelMateria, txtNombreMateria, txtSemestreMateria});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonActualizar, jButtonCrear, jButtonEliminar, jButtonLeer, jButtonLimpiar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreMateria)
                    .addComponent(jLabelSemestreMateria)
                    .addComponent(jLabelNivelMateria)
                    .addComponent(jLabelHorasMateria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHorasMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNivelMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSemestreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonLimpiar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonCrear)
                        .addComponent(jButtonLeer)
                        .addComponent(jButtonActualizar)
                        .addComponent(jButtonEliminar)))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelCodigoMateria, jLabelHorasMateria, jLabelNivelMateria, jLabelNombreMateria, jLabelSemestreMateria});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCodigoMateria, txtHorasMateria, txtNivelMateria, txtNombreMateria, txtSemestreMateria});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        limpiarTabla();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        int confirmación = JOptionPane.showConfirmDialog(null, "Esta acción afectará a todos los registros relacionados en el sistema. ¿Está segur@ que desea eliminar?", "Confirmar borrado", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (confirmación == 0) {
        int filaseleccionada = jTableMaterias.getSelectedRow();
        String idBorrar;
        if (filaseleccionada != -1) {
            idBorrar = ((String) jTableMaterias.getValueAt(filaseleccionada, 0));
            try {
                Connection conn = Conexion.conectar();
                String delete1 = "SET foreign_key_checks = 0";
                String delete2 = "delete from materia where idMateria = ? ";
                String delete3 = "SET foreign_key_checks = 1";
                PreparedStatement sentencia1 = conn.prepareStatement(delete1);
                PreparedStatement sentencia2 = conn.prepareStatement(delete2);
                PreparedStatement sentencia3 = conn.prepareStatement(delete3);
                sentencia2.setString(1, idBorrar);
                sentencia1.executeUpdate();
                int rowsDeleted = sentencia2.executeUpdate();
                sentencia3.executeUpdate();                
                conn.close();
                limpiarTabla();
                verMaterias();
            } catch (SQLException ex) {
                Logger.getLogger(Materia.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar una fila");
        }
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        int filaseleccionada = jTableMaterias.getSelectedRow();
        String idActualizar;
        if (filaseleccionada != -1) {
            idActualizar = ((String) jTableMaterias.getValueAt(filaseleccionada, 0));
            try {
                Connection conn = Conexion.conectar();
                String update1 = "update materia set Nombre_Materia= ? where idMateria = ? ";
                PreparedStatement sentencia1 = conn.prepareStatement(update1);
                String nameUpdated=JOptionPane.showInputDialog("Escriba el nuevo nombre de la Materia: ");
                sentencia1.setString(1, nameUpdated);
                sentencia1.setString(2, idActualizar);
                int rowsUpdated1 = sentencia1.executeUpdate();
                String update2 = "update materia set idSemestre= ? where idMateria = ? ";
                PreparedStatement sentencia2 = conn.prepareStatement(update2);
                String semesterUpdated=JOptionPane.showInputDialog("Escriba la nueva ubicación semestral: ");
                sentencia2.setString(1, semesterUpdated);
                sentencia2.setString(2, idActualizar);
                int rowsUpdated2 = sentencia2.executeUpdate();
                String update3 = "update materia set nivel= ? where idMateria = ? ";
                PreparedStatement sentencia3 = conn.prepareStatement(update3);
                String levelUpdated=JOptionPane.showInputDialog("Escriba el nuevo nivel: ");
                sentencia3.setString(1, levelUpdated);
                sentencia3.setString(2, idActualizar);
                int rowsUpdated3 = sentencia3.executeUpdate();
                String update4 = "update materia set horas= ? where idMateria = ? ";
                PreparedStatement sentencia4 = conn.prepareStatement(update4);
                String hoursUpdated=JOptionPane.showInputDialog("Escriba la nueva cantidad de horas: ");
                sentencia4.setString(1, hoursUpdated);
                sentencia4.setString(2, idActualizar);
                int rowsUpdated4 = sentencia4.executeUpdate();
                conn.close();
                limpiarTabla();
                verMaterias();
            } catch (SQLException ex) {
                Logger.getLogger(Materia.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar una fila");
        }
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeerActionPerformed
        try {
            limpiarTabla();
            verMaterias();
        } catch (SQLException ex) {
            Logger.getLogger(Materia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonLeerActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        crearMateria();
    }//GEN-LAST:event_jButtonCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonLeer;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCodigoMateria;
    private javax.swing.JLabel jLabelHorasMateria;
    private javax.swing.JLabel jLabelNivelMateria;
    private javax.swing.JLabel jLabelNombreMateria;
    private javax.swing.JLabel jLabelSemestreMateria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMaterias;
    private javax.swing.JTextField txtCodigoMateria;
    private javax.swing.JTextField txtHorasMateria;
    private javax.swing.JTextField txtNivelMateria;
    private javax.swing.JTextField txtNombreMateria;
    private javax.swing.JTextField txtSemestreMateria;
    // End of variables declaration//GEN-END:variables
}
