package salonesupn;

import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

public class Vista extends javax.swing.JFrame {

    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneVistas = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCrear = new javax.swing.JMenu();
        jMenuItemMateria = new javax.swing.JMenuItem();
        jMenuItemGrupo = new javax.swing.JMenuItem();
        jMenuItemSalon = new javax.swing.JMenuItem();
        jMenuItemDocente = new javax.swing.JMenuItem();
        jMenuAcciones = new javax.swing.JMenu();
        jMenuItemAsignarMateria = new javax.swing.JMenuItem();
        jMenuItemAsignarProfe = new javax.swing.JMenuItem();
        jMenuItemAsignarSalon = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItemCreditos = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));

        javax.swing.GroupLayout jDesktopPaneVistasLayout = new javax.swing.GroupLayout(jDesktopPaneVistas);
        jDesktopPaneVistas.setLayout(jDesktopPaneVistasLayout);
        jDesktopPaneVistasLayout.setHorizontalGroup(
            jDesktopPaneVistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jDesktopPaneVistasLayout.setVerticalGroup(
            jDesktopPaneVistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 751, Short.MAX_VALUE)
        );

        jMenuCrear.setText("Crear");

        jMenuItemMateria.setText("Materia");
        jMenuItemMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMateriaActionPerformed(evt);
            }
        });
        jMenuCrear.add(jMenuItemMateria);

        jMenuItemGrupo.setText("Grupo");
        jMenuItemGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGrupoActionPerformed(evt);
            }
        });
        jMenuCrear.add(jMenuItemGrupo);

        jMenuItemSalon.setText("Salon");
        jMenuItemSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalonActionPerformed(evt);
            }
        });
        jMenuCrear.add(jMenuItemSalon);

        jMenuItemDocente.setText("Docente");
        jMenuItemDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDocenteActionPerformed(evt);
            }
        });
        jMenuCrear.add(jMenuItemDocente);

        jMenuBar1.add(jMenuCrear);

        jMenuAcciones.setText("Acciones");

        jMenuItemAsignarMateria.setText("Asignar materia a grupo");
        jMenuItemAsignarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAsignarMateriaActionPerformed(evt);
            }
        });
        jMenuAcciones.add(jMenuItemAsignarMateria);

        jMenuItemAsignarProfe.setText("Asignar profe a grupo");
        jMenuItemAsignarProfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAsignarProfeActionPerformed(evt);
            }
        });
        jMenuAcciones.add(jMenuItemAsignarProfe);

        jMenuItemAsignarSalon.setText("Asignar salon a grupo");
        jMenuItemAsignarSalon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAsignarSalonActionPerformed(evt);
            }
        });
        jMenuAcciones.add(jMenuItemAsignarSalon);

        jMenuBar1.add(jMenuAcciones);

        jMenuSalir.setText("Salir");

        jMenuItemCreditos.setText("Creditos");
        jMenuItemCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCreditosActionPerformed(evt);
            }
        });
        jMenuSalir.add(jMenuItemCreditos);

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuSalir.add(jMenuItemSalir);

        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneVistas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPaneVistas)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDocenteActionPerformed
        Profesores profesTabla = new Profesores();       
        jDesktopPaneVistas.add(profesTabla);       
        profesTabla.show();
    }//GEN-LAST:event_jMenuItemDocenteActionPerformed

    private void jMenuItemMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMateriaActionPerformed
        //Crear objeto y llamar método
        Materia materiaTabla = new Materia();
        //Cargar en DesktopPane
        jDesktopPaneVistas.add(materiaTabla);
        //Volver visible
        materiaTabla.show();
    }//GEN-LAST:event_jMenuItemMateriaActionPerformed

    private void jMenuItemGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGrupoActionPerformed
        Grupo grupoTabla = new Grupo();       
        jDesktopPaneVistas.add(grupoTabla);       
        grupoTabla.show();
    }//GEN-LAST:event_jMenuItemGrupoActionPerformed

    private void jMenuItemSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalonActionPerformed
        Salon salonTabla = new Salon();       
        jDesktopPaneVistas.add(salonTabla);       
        salonTabla.show();
    }//GEN-LAST:event_jMenuItemSalonActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCreditosActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Elaborador por: \n"
                + "Sebastian Pineda Bautista\n"
                + "Version 1 - 2022\n"
                + "Con cariño para la UPN");
    }//GEN-LAST:event_jMenuItemCreditosActionPerformed

    private void jMenuItemAsignarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAsignarMateriaActionPerformed
        AsignarMaterias asignMaterTabla = new AsignarMaterias();       
        jDesktopPaneVistas.add(asignMaterTabla);       
        asignMaterTabla.show();
    }//GEN-LAST:event_jMenuItemAsignarMateriaActionPerformed

    private void jMenuItemAsignarProfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAsignarProfeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAsignarProfeActionPerformed

    private void jMenuItemAsignarSalonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAsignarSalonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAsignarSalonActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
        Conexion.conectar();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneVistas;
    private javax.swing.JMenu jMenuAcciones;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCrear;
    private javax.swing.JMenuItem jMenuItemAsignarMateria;
    private javax.swing.JMenuItem jMenuItemAsignarProfe;
    private javax.swing.JMenuItem jMenuItemAsignarSalon;
    private javax.swing.JMenuItem jMenuItemCreditos;
    private javax.swing.JMenuItem jMenuItemDocente;
    private javax.swing.JMenuItem jMenuItemGrupo;
    private javax.swing.JMenuItem jMenuItemMateria;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemSalon;
    private javax.swing.JMenu jMenuSalir;
    // End of variables declaration//GEN-END:variables
}
